/**
 * FEATURE: AUTOMATION_READY (Premium)
 *
 * Converts AI-structured automation steps into Cypress test scripts.
 * Input: tests[] from aiAutomationService — each step has { action, selector, value, assertion }
 */

function assertionToCypress(selector, assertion) {
  if (!assertion || !selector) return null;
  const sel = JSON.stringify(selector);
  const exp = assertion.expected != null ? JSON.stringify(String(assertion.expected)) : null;
  switch (assertion.type) {
    case 'visible':  return `    cy.get(${sel}).should('be.visible');`;
    case 'hidden':   return `    cy.get(${sel}).should('not.exist');`;
    case 'contains': return `    cy.get(${sel}).should('contain', ${exp || '""'});`;
    case 'equals':   return `    cy.get(${sel}).should('have.text', ${exp || '""'});`;
    default:         return `    cy.get(${sel}).should('be.visible');`;
  }
}

function stepToCypress(step) {
  const { action, selector, value, assertion } = step;
  const sel = selector ? JSON.stringify(selector) : null;
  const val = value != null ? JSON.stringify(String(value)) : null;

  switch (action) {
    case 'navigate':
      return `    cy.visit(${val || sel || JSON.stringify('/')});`;
    case 'click':
      return `    cy.get(${sel}).click();`;
    case 'type':
      return `    cy.get(${sel}).type(${val || '""'});`;
    case 'select':
      return `    cy.get(${sel}).select(${val || '""'});`;
    case 'assert':
      return assertionToCypress(selector, assertion) || `    cy.get(${sel}).should('be.visible');`;
    default:
      return `    // ${action}${selector ? ` → ${selector}` : ''}`;
  }
}

function generateCypress(aiTests) {
  const lines = [
    `// Generated by Quantix — Automation Ready`,
    ``,
    `describe('Quantix Test Suite', () => {`,
  ];

  aiTests.forEach((t) => {
    const title = (t.title || '').replace(/'/g, "\\'");
    lines.push(`  it('${title}', () => {`);

    (t.steps || []).forEach((step) => {
      lines.push(stepToCypress(step));
    });

    lines.push(`  });`);
    lines.push(``);
  });

  lines.push(`});`);
  return lines.join('\n');
}

module.exports = { generateCypress };
