/**
 * FEATURE: AUTOMATION_READY (Premium)
 *
 * Converts structured automation steps into Playwright test scripts.
 * Input: tests[] from templateConverter / aiAutomationService
 * Each step has { action, selector, value, assertion } or { action: 'multitype', fields }
 */

function assertionToPlaywright(selector, assertion) {
  if (!assertion) return null;
  const exp = assertion.expected != null ? JSON.stringify(String(assertion.expected)) : '""';

  // URL / redirect assertion — no selector needed
  if (assertion.type === 'url') {
    const path = assertion.expected || '/';
    return `  await expect(page).toHaveURL(expect.stringContaining(${JSON.stringify(path)}));`;
  }

  if (!selector) return null;
  const sel = JSON.stringify(selector);

  switch (assertion.type) {
    case 'visible':
      return `  await expect(page.locator(${sel})).toBeVisible();`;
    case 'hidden':
      return `  await expect(page.locator(${sel})).toBeHidden();`;
    case 'contains':
      return `  await expect(page.getByText(${exp})).toBeVisible();`;
    case 'equals':
      return `  await expect(page.locator(${sel})).toHaveText(${exp});`;
    default:
      return `  await expect(page.locator(${sel})).toBeVisible();`;
  }
}

function stepToPlaywright(step) {
  const { action, selector, value, assertion, fields } = step;
  const sel = selector ? JSON.stringify(selector) : null;
  const val = value != null ? JSON.stringify(String(value)) : null;

  switch (action) {
    case 'navigate':
      return [`  await page.goto(${val || sel || JSON.stringify('/')});`];

    case 'click':
      return [`  await page.click(${sel});`];

    case 'type':
      return [`  await page.fill(${sel}, ${val || '""'});`];

    case 'multitype':
      // Expand each field into its own page.fill() line
      return (fields || []).map(
        (f) => `  await page.fill(${JSON.stringify(f.selector)}, ${JSON.stringify(f.value)});`
      );

    case 'select':
      return [`  await page.selectOption(${sel}, ${val || '""'});`];

    case 'assert': {
      const line = assertionToPlaywright(selector, assertion);
      return [line || `  await expect(page.locator(${sel || '"body"'})).toBeVisible();`];
    }

    default:
      return [`  // ${action}${selector ? ` → ${selector}` : ''}`];
  }
}

function generatePlaywright(aiTests) {
  const lines = [
    `import { test, expect } from '@playwright/test';`,
    ``,
    `// Generated by Quantix — Automation Ready`,
    ``,
    `test.describe('Quantix Test Suite', () => {`,
  ];

  aiTests.forEach((t) => {
    const title = (t.title || '').replace(/'/g, "\\'");
    lines.push(`  test('${title}', async ({ page }) => {`);

    (t.steps || []).forEach((step) => {
      stepToPlaywright(step).forEach((line) => lines.push(line));
    });

    lines.push(`  });`);
    lines.push(``);
  });

  lines.push(`});`);
  return lines.join('\n');
}

module.exports = { generatePlaywright };
