/**
 * FEATURE: AUTOMATION_READY (Premium)
 *
 * Converts AI-structured automation steps into Playwright test scripts.
 * Input: tests[] from aiAutomationService — each step has { action, selector, value, assertion }
 */

function assertionToPlaywright(selector, assertion) {
  if (!assertion || !selector) return null;
  const sel = JSON.stringify(selector);
  const exp = assertion.expected != null ? JSON.stringify(String(assertion.expected)) : null;
  switch (assertion.type) {
    case 'visible':  return `  await expect(page.locator(${sel})).toBeVisible();`;
    case 'hidden':   return `  await expect(page.locator(${sel})).toBeHidden();`;
    case 'contains': return `  await expect(page.locator(${sel})).toContainText(${exp || '""'});`;
    case 'equals':   return `  await expect(page.locator(${sel})).toHaveText(${exp || '""'});`;
    default:         return `  await expect(page.locator(${sel})).toBeVisible();`;
  }
}

function stepToPlaywright(step) {
  const { action, selector, value, assertion } = step;
  const sel = selector ? JSON.stringify(selector) : null;
  const val = value != null ? JSON.stringify(String(value)) : null;

  switch (action) {
    case 'navigate':
      return `  await page.goto(${val || sel || JSON.stringify('/')});`;
    case 'click':
      return `  await page.click(${sel});`;
    case 'type':
      return `  await page.fill(${sel}, ${val || '""'});`;
    case 'select':
      return `  await page.selectOption(${sel}, ${val || '""'});`;
    case 'assert':
      return assertionToPlaywright(selector, assertion) || `  await expect(page.locator(${sel})).toBeVisible();`;
    default:
      return `  // ${action}${selector ? ` → ${selector}` : ''}`;
  }
}

function generatePlaywright(aiTests) {
  const lines = [
    `import { test, expect } from '@playwright/test';`,
    ``,
    `// Generated by Quantix — Automation Ready`,
    ``,
    `test.describe('Quantix Test Suite', () => {`,
  ];

  aiTests.forEach((t) => {
    const title = (t.title || '').replace(/'/g, "\\'");
    lines.push(`  test('${title}', async ({ page }) => {`);

    (t.steps || []).forEach((step) => {
      lines.push(stepToPlaywright(step));
    });

    lines.push(`  });`);
    lines.push(``);
  });

  lines.push(`});`);
  return lines.join('\n');
}

module.exports = { generatePlaywright };
