/**
 * FEATURE: AUTOMATION_READY (Premium)
 *
 * Converts AI-structured automation steps into a Postman Collection v2.1.
 * Input: tests[] from aiAutomationService — each step has { action, selector, value, assertion }
 * For Postman, action is always "api_request", selector = endpoint, value = payload.
 */

function inferHttpMethod(endpoint, value) {
  if (!endpoint) return 'POST';
  const ep = endpoint.toLowerCase();
  const val = value ? value.toString().toLowerCase() : '';
  if (ep.includes('delete') || val.includes('delete')) return 'DELETE';
  if (ep.includes('update') || ep.includes('edit') || val.includes('put')) return 'PUT';
  if (ep.includes('list') || ep.includes('fetch') || ep.includes('get') || ep.endsWith('s')) {
    if (!val || val === 'null') return 'GET';
  }
  return 'POST';
}

function buildPostmanTests(assertion) {
  if (!assertion) return [];
  const scripts = [];
  if (assertion.type === 'status' && assertion.expected) {
    scripts.push(`pm.test("Status ${assertion.expected}", () => pm.response.to.have.status(${assertion.expected}));`);
  }
  if (assertion.type === 'equals' && assertion.expected) {
    const exp = JSON.stringify(assertion.expected);
    scripts.push(`pm.test("Response equals ${assertion.expected}", () => {`);
    scripts.push(`  const json = pm.response.json();`);
    scripts.push(`  pm.expect(JSON.stringify(json)).to.include(${exp});`);
    scripts.push(`});`);
  }
  if (assertion.type === 'contains' && assertion.expected) {
    scripts.push(`pm.test("Response contains expected value", () => {`);
    scripts.push(`  pm.expect(pm.response.text()).to.include(${JSON.stringify(assertion.expected)});`);
    scripts.push(`});`);
  }
  return scripts;
}

function buildRequestItem(step, idx) {
  const endpoint = step.selector || '/api/endpoint';
  const rawUrl = endpoint.startsWith('http') ? endpoint : `{{baseUrl}}${endpoint}`;
  const method = inferHttpMethod(endpoint, step.value);

  let payload = null;
  if (step.value && step.value !== 'null') {
    try {
      payload = typeof step.value === 'string' ? JSON.parse(step.value) : step.value;
    } catch {
      payload = { data: step.value };
    }
  }

  const request = {
    method,
    header: [
      { key: 'Content-Type', value: 'application/json' },
      { key: 'Authorization', value: 'Bearer {{token}}' }
    ],
    url: {
      raw: rawUrl,
      host: ['{{baseUrl}}'],
      path: endpoint.replace(/^\//, '').split('/')
    }
  };

  if (payload && method !== 'GET') {
    request.body = {
      mode: 'raw',
      raw: JSON.stringify(payload, null, 2),
      options: { raw: { language: 'json' } }
    };
  }

  const testScripts = buildPostmanTests(step.assertion);

  return {
    name: `${method} ${endpoint}`,
    request,
    event: testScripts.length > 0
      ? [{ listen: 'test', script: { exec: testScripts, type: 'text/javascript' } }]
      : []
  };
}

function generatePostman(aiTests) {
  const collection = {
    info: {
      name: 'Quantix Collection — Automation Ready',
      description: 'Generated by Quantix AI — executable API test collection',
      schema: 'https://schema.getpostman.com/json/collection/v2.1.0/collection.json'
    },
    variable: [
      { key: 'baseUrl', value: 'https://your-api.example.com', type: 'string' },
      { key: 'token', value: '', type: 'string' }
    ],
    item: aiTests.map((t) => ({
      name: t.title,
      item: (t.steps || [])
        .filter((s) => s.action === 'api_request')
        .map((s, idx) => buildRequestItem(s, idx))
    }))
  };

  return JSON.stringify(collection, null, 2);
}

module.exports = { generatePostman };
